config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :events, only: %i[index show] do
    resources :bookmarks, only: %i[create]
  end

  resources :tickets, only: %i[show]

  get '/marketplace', to: 'tokens#index'

  resources :tokens, only: %i[show update] do # index will be the 'marketplace', where the search logic happens
    resources :cart_items, only: %i[create]
  end

  # We might want to relocate the marketplace to a subdomain such as "https://marketplace.domain.com/" later

  resource :cart, only: %i[show] do
    resources :transactions, only: %i[show create]
  end

  resources :cart_items, only: %i[destroy]

  post '/tokens/add', to: 'cart_items#add'

  resources :users, only: %i[index] do
    get '/transactions', to: 'transactions#index'
    get '/collection', to: 'users#collection'
  end
  
  get '/about', to: 'pages#about', as: "about"
  resources :bookmarks, only: %i[index destroy]
end

# about us page

app/views/shared/_card.html.erb
<div class="event-card">
  <%= link_to "/events/#{event.id}", class: "event-card-img" do %>
    <div class="event-location-tag">
      <p class="event-location-tag-text"><i class="fas fa-location-arrow location-icon"></i><%= event.city %></p>
    </div>
    <%= image_tag event.image_url, class: "event-card-img" %>
  <% end %>
  <div class="event-card-content">
    <h4><%= link_to event.name, "/events/#{event.id}" %></h4>
    <div style="color: #7B7B7B">
      <%= link_to "/events/#{event.id}", class: "event-card-img" do %>
      <p><%= event.start_time.strftime('%d/%m/%Y') %></p>
      <div>
        <div class="d-flex justify-content-center">
          <div class="d-flex align-items-center">
            <%if event.tokens.count == 0 %>
              <p>SOLD OUT</p>
            <%else%>
              <i class="fas fa-ticket-alt ticket-icon"></i><%= event.tokens.count %>
            <%end%>
          </div>
        </div>
      </div>
      <% end %>
      <% if current_user %>
        <% if event.bookmarks.pluck(:user_id).include?(current_user.id) == true %>
          <% bookmark = event.bookmarks.find_by(user_id:current_user.id) %>
          <%=button_to bookmark_path(bookmark), method: :delete, remote: true do %>
            <i class="fas fa-heart heart-icon"></i>
          <% end %>
        <% else %>
          <%= button_to event_bookmarks_path(event), method: :post, remote: true do %>
            <i class="far fa-heart heart-icon"> </i>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <i class="far fa-heart heart-icon"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>

  <div class="footer-hr"></div>

  <div class="footer-content">
    <div class="footer-cta">
      <div class="newsletter">
        <h4><strong>Stay tuned</strong></h4>
        </br>
        <form action="">
          <input type="search" id="newsletter" name="mail" placeholder="Add you email and join our newsletter ..." value="">
          <button type="submit" class="renbo-btn">Sign up</i></button>
        </form>
      </div>
      <div class="socials">
        <h4><strong>Join us there</strong></h4>
        <a href="www.facebook.com"><i class="fab fa-facebook-f"></a></i>
        <a href="www.instagram.com"><i class="fab fa-instagram"></i></a>
        <a href="www.twitter.com"><i class="fab fa-twitter"></i></a>
        <a href="www.linkedin.com"><i class="fab fa-linkedin-in"></i></a>
      </div>
    </div>

    <div class="footer-nav">
      <div class="footer-nav-col">
        <h5><strong>Events</strong></h5>
        </br>
        <a href="https://www.renbo.io/events?q=electronic"><p>Electronic</p></a>
        <a href="https://www.renbo.io/events?q=hip-hop"><p>Hip-hop</p></a>
        <a href="https://www.renbo.io/events?q=rock"><p>Rock</p></a>
        <a href="https://www.renbo.io/events?q=classical"><p>Classical</p></a>
        <a href="https://www.renbo.io/events?q=jazz"><p>Jazz</p></a>
        <a href="https://www.renbo.io/events?q=jazz"><p>Pop</p></a>
      </div>
      <div class="footer-nav-col">
        <h5><strong>Marketplace</strong></h5>
        </br>
        <a href="https://www.renbo.io/events?q=festival"><p>Browse</p></a>
        <a href=""><p>Best Deals</p></a>
        <a href=""><p>Last Minute</p></a>
      </div>
      <div class="footer-nav-col">
        <h5><strong>Account</strong></h5>
        </br>
        <a href=""><p>Profile</p></a>
        <a href=""><p>Wallet</p></a>
        <a href=""><p>Bookmarks</p></a>
        <a href=""><p>Recent Transactions</p></a>
      </div>
      <div class="footer-nav-col">
        <h5><strong>Renbo</strong></h5>
        </br>
        <a href="https://www.renbo.io/about"><p>About Us</p></a>
        <a href=""><p>Careers</p></a>
        <a href=""><p>Invest</p></a>
      </div>
    </div>
  </div>

  <div class="footer-hr"></div>

  <p id="copyright">@Renbo 2022</p>

</footer>

app/views/shared/_genre.html.erb
  <div class="genre grow home-element">
    <%= link_to events_path(q: "", genre: genre) do %>
      <%= image_tag "genres/#{genre}.png", class:"genre-img" %>
      <h4 class="text-center"><%= genre.capitalize %></h4>
    <% end %>
  </div>

app/views/shared/_infinite_carousel.html.erb
<div class="carousel2">

<div class="container2">
    <input type="radio" name="slider" id="item-1" checked>
    <input type="radio" name="slider" id="item-2">
    <input type="radio" name="slider" id="item-3">
  <div class="cards3">
    <label class="card2" for="item-1" id="song-1">

      <%= image_tag "nft1.png", class:"caro-image" %>
      <%= image_tag "nft1.png", class:"shadow-image" %>
    </label>
    <label class="card2" for="item-2" id="song-2">

      <%= image_tag "nft2.png", class:"caro-image" %>
      <%= image_tag "nft2.png", class:"shadow-image" %>
    </label>
    <label class="card2" for="item-3" id="song-3">
      <%= image_tag "nft3.png", class:"caro-image" %>
      <%= image_tag "nft3.png", class:"shadow-image" %>
    </label>

  </div>

</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-transparent navbar navbar-expand-sm navbar-light navbar-lewagon" data-hide-nav-target="nav">
  <div class="container">
    <%= link_to "/", class: "navbar-brand" do %>
    <div class="nav-start">
      <%= image_tag "renbologo.png" %>
      <h4 class="nav-logo-heading">Renbo</h4>
      <%# <h4 class="nav-logo-heading-p1">Ren</h4>
      <h4 class="nav-logo-heading-p2">bo</h4> %>
    </div>
    <% end %>

    <%= render "shared/searchbar", hidden: ("invisible" if action_name =="home"), parent: "searchbar-nav" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="nav-end">
      <%= link_to marketplace_path do %>
        <button class="renbo-btn">Marketplace</button>
      <% end %>
      <%= link_to cart_path do %>
        <button><i class="fas fa-shopping-cart"></i></button>
      <% end %>
      <% if current_user %>
        <div class="dropdown">
          <button type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <% if current_user.avatar.attached? %>
              <%= cl_image_tag current_user.avatar.key, class: "avatar" %>
            <% else %>
              <i class="fas fa-user"></i>
            <% end %>
          </button>
          <ul class="dropdown-menu nav-dropdown" aria-labelledby="dropdownMenuButton1">
            <li class="nav-drop-item"><%= link_to "Collection", user_collection_path(current_user) %></li>
            <li class="nav-drop-item"><%= link_to "Bookmarks", bookmarks_path  %></li>
            <li class="nav-drop-item"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      <% else %>
        <div class="dropdown">
            <button type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fas fa-user"></i>
            </button>
          <ul class="dropdown-menu nav-dropdown" aria-labelledby="dropdownMenuButton1">
            <li class="nav-drop-item"><%= link_to "Sign in", new_user_session_path %></li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar_cart.html.erb
<div class="cart-nav ticket-table d-none" data-navbar-cart-target="cart">
  <div class="table-tickets-sm">
    <% if current_user %>
      <% current_user.carts.last.cart_items.each do |cart_item| %>
        <div class="table-row-sm">
          <div class="table-image-sm">
            <img width="95%" height="95%" src="<%= cart_item.token.ticket.image_url %>" alt="">
          </div>
          <p class="table-col-sm"><%= cart_item.token.ticket.title %></p>
          <p class="table-col-sm"><strong>$<%= cart_item.token.price.truncate %></strong></p>
          <div class="table-col-price-sm">
            <%= link_to cart_item_path(cart_item), method: :delete do %>
                <i class="fas fa-trash-alt"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="table-bottom">
    <p class="table-header-empty-sm"></p>
    <p class="total-price-text table-col-lg"><strong>Total price:</strong></p>
    <p class="table-total-price table-col-lg"><strong>$<%= current_user ? current_user.carts.last.total_price : 0 %></strong></p>
    <p class="table-col-price-lg">
      <%= link_to cart_path do %>
        <button class="cart-nav-btn renbo-btn">Checkout</button>
      <% end %>
    </p>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<form action="/events" id="<%= parent %>" class="<%= hidden %>">
  <input type="search" id="query" name="q" placeholder="Search for an event, a city, an artist ..." value="<%= params['q'] || "" %>">
  <button type="submit"><i class="fas fa-search mglass"></i></button>
</form>

app/views/shared/_table.html.erb
<div class="ticket-table">
  <div class="table-title table-top">
    <h5>Marketplace // <%= event.name %></h5>
  </div>
  <div class="table-header table-top">
    <p class="table-header-empty"></p>
    <p class="table-col"><strong>Ticket Details</strong></p>
    <p class="table-col"><strong>Status</strong></p>
    <p class="table-col"><strong>Time Left</strong></p>
    <p class="table-col"><strong>Price</strong></p>
    <p class="table-col-price"></p>
  </div>
  <div class="table-tickets">
    <% tokens.each do |token| %>
      <% if token.status == "available" %>
        <div class="table-row" id="token-<%= token.id %>">
          <div class="table-image">
            <img width="95%" height="95%" src="<%= token.ticket.image_url %>" alt="">
          </div>
          <p class="table-col"><%= token.ticket.title %> #<%= token.sequence_num %></p>
          <p class="table-col"><%= token.status.capitalize %></p>
          <p class="table-col">1d:12h:25m:10s</p>
          <p class="table-col"><strong><%= humanized_money_with_symbol(token.price) %></strong></p>
          <div class="table-col">
            <%= link_to token_path(token) do %>
            <button class="renbo-btn-sec">See ticket</button>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_ticket.html.erb
<%= link_to ticket_path(ticket) do %>
<div class="ticket-card">
  <% if ticket.VIP %>
    <div class="renbo-label vip-label"><strong>VIP</strong></div>
  <% end %>
  <div class="ticket-card-image">
      <img height="95%" width="95%" src="<%= ticket.image_url%>" alt="">
  </div>
  <div class="ticket-content">
    <h5><%= ticket.title.first(18) %></h5>
    <p><%= ticket.description.first(50) + " ..."  %></p>
  </div>
  <div class="ticket-token-num">
    <strong><i class="fas fa-ticket-alt ticket-icon"></i><%= ticket.tokens.count %></strong>
  </div>
  <div class="ticket-price-tag">
    <strong><%= humanized_money_with_symbol(ticket.original_price) %></strong>
  </div>
</div>
<% end %>

app/views/shared/_ticket_dropdown.html.erb
<div class="dropdown">
  <button class="ticket-dropdown dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    Select your unique ticket....
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <%# INSERT SEATING LOGIC HERE %>
    <% @ticket.tokens.each do |token| %>
      <% if token.status == "new" %>
        <li><a class="dropdown-item" href="#"><%= @ticket.title %> #<%= token.sequence_num %></a></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/shared/_token.html.erb
<div class="ticket-card">
  <% if vip %>
    <div class="renbo-label vip-label"><strong>VIP</strong></div>
  <% end %>
  <div class="ticket-card-image">
    <%= link_to token_path(token) do %>
      <img height="95%" width="95%" src="<%= token.ticket.image_url%>" alt="">
    <% end %>
  </div>
  <div class="ticket-content">
    <h5><%= token.ticket.title.first(18) %></h5>
    <p><%= token.ticket.description.first(50) + " ..."  %></p>
  </div>
  <div class="ticket-token-num">
    <strong>
     <i class="fas fa-ticket-alt ticket-icon"></i> #<%= token.sequence_num %>/<span style="font-size: 12px;"><%= token.ticket.tokens.count %></span>
    </strong>
  </div>
  <div class="ticket-price-tag">
    <strong><%= humanized_money_with_symbol(token.price) %></strong>
  </div>
</div>