config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :events, only: %i[index show] do
    resources :bookmarks, only: %i[create]
  end

  resources :tickets, only: %i[show]

  get '/marketplace', to: 'tokens#index'

  resources :tokens, only: %i[show update] do # index will be the 'marketplace', where the search logic happens
    resources :cart_items, only: %i[create]
  end

  # We might want to relocate the marketplace to a subdomain such as "https://marketplace.domain.com/" later

  resource :cart, only: %i[show] do
    resources :transactions, only: %i[show create]
  end

  resources :cart_items, only: %i[destroy]

  post '/tokens/add', to: 'cart_items#add'

  resources :users, only: %i[index] do
    get '/transactions', to: 'transactions#index'
    get '/collection', to: 'users#collection'
  end
  
  get '/about', to: 'pages#about', as: "about"
  resources :bookmarks, only: %i[index destroy]
end

# about us page

app/models/token.rb
class Token < ApplicationRecord
  has_many :cart_item
  belongs_to :ticket
  belongs_to :user
  has_one :event, through: :ticket

  monetize :price_cents

  def set_sequence
    self.sequence_num = Token.where(ticket_id: self.ticket_id).count + 1
  end

  before_create :set_sequence

  validates :status, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  # validates :NFT_id, presence: true
  # validates :unlockable, presence: true
  # validates: unlocked, presence: true

  def set_sequence
    self.sequence_num = Token.where(ticket_id: self.ticket_id).count + 1
  end

  include PgSearch::Model
  pg_search_scope :extended_search,	# Name, Category, Music Genre, Artist, Country, City, Description
                  associated_against: {
                    ticket: %i[title description],
                    event: %i[name category music_genre country city description]
                  },
                  using: { tsearch: { prefix: true }, trigram: { word_similarity: true } }

  pg_search_scope :category_search,	# Category
                  associated_against: { event: %i[category] },
                  using: { tsearch: { prefix: true }, trigram: { word_similarity: true } }

  pg_search_scope :country_search,	# Country
                  associated_against: { event: %i[country] },
                  using: { tsearch: { prefix: true }, trigram: { word_similarity: true } }

  pg_search_scope :city_search,	# City
                  associated_against: { event: %i[city] },
                  using: { tsearch: { prefix: true }, trigram: { word_similarity: true } }

end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @tokens = Token.all.joins(:event)

    if params['evt-date'].present?
      @tokens = @tokens.where("events_tokens.start_time < ?", DateTime.now) if params['evt-date'] == "past"
      @tokens = @tokens.where(events_tokens: { start_time: DateTime.now.beginning_of_month..DateTime.now.end_of_month }) if params['evt-date'] == "month"
      @tokens = @tokens.where(events_tokens: { start_time: DateTime.now.beginning_of_year..DateTime.now.end_of_year }) if params['evt-date'] == "year"
      @tokens = @tokens.where("events_tokens.start_time > ?", DateTime.now.end_of_year) if params['evt-date'] == "later"
    end

    # @tokens = @tokens # To modify with status filter (for sale)

    @tokens = @tokens.extended_search(params['q']) if params['q'].present?
    @tokens = @tokens.category_search(params['category']) if params['category'].present?

    @tokens = @tokens.where("price_cents > #{params['price-min'].to_i * 100}") if params['price-min'].present?
    @tokens = @tokens.where("price_cents < #{params['price-max'].to_i * 100}") if params['price-max'].present?

    @tokens = @tokens.country_search(params['country']) if params['country'].present?
    @tokens = @tokens.city_search(params['city']) if params['city'].present?

    if params['rank'].present?
      @tokens = @tokens.order(:title) if params['rank'] == "az"
      @tokens = @tokens.order(title: :desc) if params['rank'] == "za"
      @tokens = @tokens.order(:price_cents) if params['rank'] == "cheap"
      @tokens = @tokens.order(price_cents: :desc) if params['rank'] == "expensive"

    else
      @tokens = @tokens.shuffle
    end

  end

  def show
    @token = Token.find(params[:id])

    redirect_to request.referer.to_s unless @token.status == "available"
  end

end

app/views/tokens/index.html.erb
<div class="renbo-container">
  <div class="market-top">
    <form action="/marketplace" id="searchbar-market" class="">
      <input type="search" id="query" name="q" placeholder="Search for a ticket ..." value="<%= params['q'] || "" %>">
      <button type="submit"><i class="fas fa-search mglass"></i></button>
    </form>

    <div id="sort-btn" data-controller="marketplace-sort">
      <button class="renbo-btn-sec" data-action="click->marketplace-sort#toggle">Sort by</button>
      <div class="sort-box d-none" data-marketplace-sort-target="box">
          <button form="marketplace-form" type="submit" name="rank" value="az">From A to Z</button>
          <hr>
          <button form="marketplace-form" type="submit" name="rank" value="za">From Z to A</button>
          <hr>
          <button form="marketplace-form" type="submit" name="rank" value="cheap">Price (Low to High)</button>
          <hr>
          <button form="marketplace-form" type="submit" name="rank" value="exp">Price (High to Low)</button>
      </div>
    </div>
  </div>

  <div class="market-main">

    <div class="market-right-container">
      <div class="market-filters">
        <form id="marketplace-form" action="/marketplace">

          <div class="cat-filter">
            <h4>Category</h4>
            <select name="category" class="mkt-input-lg" onchange="this.form.submit()">
              <option value="">Category ...</option>
              <% Event.categories.each do |category| %>
              <option value="<%= category %>" <%= "selected" if params['category'] == category %>><%= category %></option>
              <% end %>
            </select>
          </div>

          <div class="price-filter">
            <h4>Price</h4>
            <div id="price-inputs">
              <input type="number" name="price-min" class="mkt-input-sm" placeholder="From $ ..." onchange="this.form.submit()" value="<%= params['price-min'] || "" %>">
              <input type="number" name="price-max" class="mkt-input-sm" placeholder="... To $" onchange="this.form.submit()" value="<%= params['price-max'] || "" %>">
            </div>
          </div>

          <div class="status-filter">
            <h4>Status</h4>
            <div id="status-check">
              <input type="checkbox" name="stlocked" id="check-locked" value="locked" onchange="this.form.submit()" <%= "checked" if params['stlocked'].present? %>/>
              <label for="check-locked">Locked</label>
              <br>
              <input type="checkbox" name="stunlocked" id="check-unlocked" value="unlocked" onchange="this.form.submit()" <%= "checked" if params['stunlocked'].present? %>/>
              <label for="check-unlocked">Unlocked</label>
            </div>
          </div>

          <div class="price-filter">
            <h4>Location</h4>
            <div id="price-inputs">
              <input name="country" class="mkt-input-sm" placeholder="Country ..." onchange="this.form.submit()" value="<%= params['country'] || "" %>">
              <input name="city" class="mkt-input-sm" placeholder="City ..." onchange="this.form.submit()" value="<%= params['city'] || "" %>">
            </div>
          </div>

          <div class="date-filter">
            <h4>Event Date</h4>
            <div id="date-choice">
              <input id="date-past" type="radio" name="evt-date" value="" onchange="this.form.submit()" <%= "checked" if params['evt-date'] == "" || !params['event'].present? %>>
              <label for="date-past">All</label><br>
              <input id="date-past" type="radio" name="evt-date" value="past" onchange="this.form.submit()" <%= "checked" if params['evt-date'] == "past" %>>
              <label for="date-past">Past</label><br>
              <input id="date-this-month" type="radio" name="evt-date" value="month" onchange="this.form.submit()" <%= "checked" if params['evt-date'] == "month" %>>
              <label for="date-this-month">This month</label><br>
              <input id="date-this-year" type="radio" name="evt-date" value="year" onchange="this.form.submit()" <%= "checked" if params['evt-date'] == "year" %>>
              <label for="date-this-year">This year</label><br>
              <input id="date-later" type="radio" name="evt-date" value="later" onchange="this.form.submit()" <%= "checked" if params['evt-date'] == "later" %>>
              <label for="date-later">Later</label><br>
            </div>
          </div>
        </form>
      </div>
    </div>

    <div class="market-left-container">
      <div class="market-results">
        <% @tokens.each do |token| %>
          <% if token.status == "available" %>
            <%= render "shared/token", token: token, tokens: @tokens, vip: false %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tokens/show.html.erb
<div class="renbo-container">

  <div class="token-top">
    <div class="token-img" style="background-image: url(<%= @token.ticket.image_url %>);">
    </div>
    <div class="token-info">
      <div class="token-box">
        <div class="token-header">
          <h2><%= @token.ticket.title %></h2>
          <h4><%= @token.event.name %></h4>
          <h4><i class="fas fa-ticket-alt ticket-icon"></i> #<%= @token.sequence_num %> <span style="font-size: 12px;">/ <%= @token.ticket.tokens.count %></span></h4>
        </div>
        <div class="token-buy">
          <h4><span style="color: #5628F5;"><%= humanized_money_with_symbol(@token.price) %></span></h4>
          <button class="renbo-btn">Buy now</button>
        </div>
      </div>
      <div class="accordion" id="token-accordion">
        <div class="accordion-item">
          <h2 class="accordion-header" id="panelsStayOpen-headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
              About the ticket
            </button>
          </h2>
          <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
            <div class="accordion-body">
              <p><%= @token.ticket.description %></p>
              <hr>
              <div class="token-event-info">
                <p><strong>Free seating</strong></p>
                <p><strong>For: <%= (2..3).to_a.sample %> days only</strong></p>
              </div>
              <u><%= link_to "See more", ticket_path(@token.ticket) %></u>
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingTwo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              About the event
            </button>
          </h2>
          <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <p><%= @token.event.description %></p>
              <hr>
              <div class="token-event-info">
                <p><strong><%=  @token.event.start_time.strftime("%d %B") %><em> to </em><%= @token.event.end_time.strftime("%d %B") %></strong></p>
                <p><strong><%= @token.event.city %>, <%= @token.event.country %></strong></p>
              </div>
              <u><%= link_to "See more", event_path(@token.event) %></u>
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingThree">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              More info
            </button>
          </h2>
          <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <p>Your NFT ticket will not only be your access to the event with exclusive perks, but your NFT ticket can be sold so you can generate revenue streams for yourself and the NFT community. Not only will you attend the even in-person, but you'll also get a virtual experience including an NFT ticket that you can save or exchange.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>