config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :events, only: %i[index show] do
    resources :bookmarks, only: %i[create]
  end

  resources :tickets, only: %i[show]

  get '/marketplace', to: 'tokens#index'

  resources :tokens, only: %i[show update] do # index will be the 'marketplace', where the search logic happens
    resources :cart_items, only: %i[create]
  end

  # We might want to relocate the marketplace to a subdomain such as "https://marketplace.domain.com/" later

  resource :cart, only: %i[show] do
    resources :transactions, only: %i[show create]
  end

  resources :cart_items, only: %i[destroy]

  post '/tokens/add', to: 'cart_items#add'

  resources :users, only: %i[index] do
    get '/transactions', to: 'transactions#index'
    get '/collection', to: 'users#collection'
  end
  
  get '/about', to: 'pages#about', as: "about"
  resources :bookmarks, only: %i[index destroy]
end

# about us page

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_one_attached :image

  belongs_to :event
  has_many :tokens

  monetize :original_price_cents

  validates :title, presence: true
  validates :description, presence: true
  validates :tier, presence: true
  validates :no_available, presence: true
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  skip_before_action :authenticate_user!
  def show
    @ticket = Ticket.find(params[:id])
    @event = @ticket.event
    @tickets = @event.tickets.where.not(id: params[:id])
    @cart_item = CartItem.new
    @cart = current_user&.carts&.last
    @cart_items = @cart&.cart_items
    @tokens_available = Token.where(ticket_id: @ticket.id, status: "new")
    @tokens_available = @tokens_available.where.not(id: current_user.carts.last.cart_items.pluck(:token_id)) if user_signed_in?
  end
end

app/views/tickets/show.html.erb
<div class="renbo-container" data-controller="ticket-dropdown">
  <div class="ticket-banner">
    <h1 class="ticket-banner-heading"><%= @ticket.title %></h1>
    <div class="ticket-banner-image" style="background-image: url(<%= @ticket.image_url %>)"></div>
    <div class="ticket-banner-content">
      <div class="ticket-banner-description">
        <p> <%= @ticket.description %>
        </p>
      </div>
      <div class="ticket-banner-details">
        <div class="ticket-banner-specifics">
        <%if @ticket.VIP%>
        <div class="renbo-label vip-label text-center"><strong>VIP</strong></div>
        <%end%>
          <p>Free Seating</p>
        </div>
        <p>For: <%= (2..3).to_a.sample %> days only</p>
        <%= humanized_money_with_symbol(@ticket.original_price) %>
      </div>
      <div class="ticket-banner-purchase">
        <%= simple_form_for @cart_item, url: tokens_add_path, remote: true, html: { class: "w-100" } do |f| %>
          <div class="d-flex justify-content-between">
            <h3><%= @tokens_available.count %> / <%= @ticket.no_available %> left</h3>
            <% if  @tokens_available.count != 0 %>
              <%= f.association :token,
                collection: @tokens_available,
                prompt: "Select your unique ticket",
                label_method: lambda { |token| "#{token.ticket.title} # #{token.sequence_num}"},
                input_html: { class: "ticket-dropdown" },
                label: false
              %>
              <% if current_user %>
                <button class="renbo-btn">Add to cart</button>
              <% else %>
                <button class="renbo-btn-sec"><%= link_to "Sign in", new_user_session_path %></button>
              <% end %>
            <% else %>
              <div class="text-center">
                <h3>Sold out ?</h3>
                <p>Try the <%= link_to "marketplace", marketplace_path, class:"mini-cart-sign-in" %> or <%= link_to "browse", "#browse", class:"mini-cart-sign-in" %> below.</p>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="ticket-info">
    <div class="ticket-show-container">
      <h2 class="tickets-show-heading" id="browse">Browse all tickets</h2>
      <%= render "shared/table", tokens: @ticket.tokens, event: @ticket.event %>
      <h2 class="tickets-show-heading">Other tickets for this event</h2>
      <div class="event-card-grid">
        <% @tickets.each do |ticket| %>
          <%= render "shared/ticket", ticket: ticket, vip: true %>
        <% end %>
      </div>
    </div>
    <div class="ticket-checkout-card">
      <h3>My cart</h3>
      <% if current_user %>
        <div class="ticket-checkout-dropdown">
          <% if @cart_items.empty? %>
            <%= simple_form_for @cart_item, url: tokens_add_path, remote: true, html: { class: "w-100" } do |f| %>
              <div class="justify-content-between">
                <%= f.association :token,
                  collection: @tokens_available,
                  prompt: "Select your unique ticket",
                  label_method: lambda { |token| "#{token.ticket.title} ##{token.sequence_num}"},
                  input_html: { class: "ticket-dropdown" },
                  label: false
                %>
                <div class="d-flex justify-content-end">
                  <button class="renbo-btn">Add to cart</button>
                </div>
              </div>
            <% end %>
          <% else %>
              <div class="ticket-checkout-summary">
                <ul class="mini-cart-list">
                  <% @cart_items.each do |item| %>
                    <li class="mini-cart-item">
                      <div class="w-50 mb-2">
                        <%= item.token.ticket.title %> #<%= item.token.sequence_num %>
                      </div>
                      <%= humanized_money_with_symbol(item.token.price) %>
                      <%= link_to "X", cart_item_path(item), method: :delete %>
                    </li>
                  <% end %>
                </ul>
              </div>
              <div class="ticket-price-summary">
                <div>
                  <p>Total:</p>
                  <%= humanized_money_with_symbol(@cart.total_price) %>
                </div>
                <button class="renbo-btn"><%= link_to "Go to cart", cart_path %></button>
              </div>
          <% end %>
        </div>
      <% else %>
        <p><%= link_to "Sign in", new_user_session_path, class:"mini-cart-sign-in" %> to add to cart.</p>
      <% end %>
    </div>
  </div>
</div>